=== malinhauglandh/exploring-norwegian-news-sources/data/da-2019-nob/avis2.dtd
<!ELEMENT document (#PCDATA | header | body)*>
<!ENTITY amp "&#38;">
<!ENTITY ndash "&#150;">
<!ENTITY lsaquo "&#8249;">
<!ENTITY rsaquo "&#8250;">
<!ENTITY ldquo "&#8220;">
<!ENTITY rdquo "&#8221;">
<!ENTITY Scaron "&#352;">
<!ENTITY scaron "&#352;">
<!ENTITY hellip "&#8230;">
<!ENTITY euro "&#8364;">
<!ENTITY permil "&#8240;">
<!ENTITY pi "&#960;">
<!ELEMENT header (#PCDATA | attribute)*>
<!ELEMENT attribute (#PCDATA)>
<!ATTLIST attribute name CDATA #IMPLIED>
<!ATTLIST attribute value CDATA #IMPLIED>
<!ATTLIST attribute frk CDATA #IMPLIED>
<!ATTLIST attribute ab CDATA #IMPLIED>
<!ELEMENT body (#PCDATA | div)*>
<!ELEMENT div (#PCDATA | p | P | mt)*>
<!ATTLIST div type CDATA #IMPLIED>
<!ATTLIST div level CDATA #IMPLIED>
<!ELEMENT p (#PCDATA | s | word | mt | b | B | i | I | em | strong | EM | STRONG | quote)*>
<!ATTLIST p id CDATA #IMPLIED>
<!ELEMENT P (#PCDATA | s | word | mt | b | B | i | I | em | strong | EM | STRONG | quote)*>
<!ATTLIST P id CDATA #IMPLIED>
<!ELEMENT b (#PCDATA | word)*>
<!ATTLIST b class CDATA #IMPLIED>
<!ELEMENT B (#PCDATA | word)*>
<!ELEMENT mt (#PCDATA | word)*>
<!ELEMENT i (#PCDATA | word)*>
<!ELEMENT I (#PCDATA | word)*>
<!ELEMENT em (#PCDATA | word)*>
<!ELEMENT EM (#PCDATA | word)*>
<!ELEMENT strong (#PCDATA | word)*>
<!ELEMENT STRONG (#PCDATA | word)*>
<!ELEMENT quote (#PCDATA | word)*>

<!-- Elements for grammatically tagged xml files -->
<!ATTLIST s admin CDATA #IMPLIED>
<!ELEMENT word (#PCDATA)>
<!ATTLIST word lemma CDATA #IMPLIED>
<!ATTLIST word features CDATA #IMPLIED>
<!ATTLIST word norm CDATA #IMPLIED>

=== malinhauglandh/exploring-norwegian-news-sources/data/db-2019-nob/DB-20190621-avokado-krigen-na-sv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="DB-20190621-avokado-krigen-na-sv.xml"/>
<attribute name="url" value="http://www.dagbladet.no/nyheter/avokado-krigen-na-svarer-de-kriminelle-med-hoyteknologi/71191717" frk="498 7 22 3095"/>
<attribute name="source" value="DB"/>
<attribute name="date" value="2019-06-21 00:52"/>
<attribute name="author" value="Halldor Hustadnes"/>
<attribute name="gender" value="M"/>
<attribute name="class1" value="nyheter"/>
<attribute name="class2" value="utenriks,avokado,nyheter,mexico"/>
<attribute name="language" value="nob"/>
</header>
<body>
<div type="title" level="1">Avokado-krigen: Nå svarer de kriminelle med høyteknologi</div>
<div type="ingress">Opp til fire lastebiler med den verdifulle frukten stjeles daglig i Mexicos delstat Michoacán.</div>
<div type="author">Halldor Hustadnes</div>
<div type="date">2019-06-21</div>
<div type="caption"><p>UMULIG: «Det er umulig å fortsette å ta disse tapene», sto det i en annonse rettet mot tyverier av lastebillass med avokado som meksikanske produsenter og eksportører igår fredag rykket inn i meksikanske aviser. Bildet er tatt i kommunen Uruapan i delstaten Michoacán i 2016. Foto: Ronaldo Schemidt/AFP/NTB Scanpix</p> <p>VEST FOR MEXICO BY: Delstaten Michoacán er det skraverte området, vest for Mexicos hovedstad Mexico by. Foto: NTB Scanpix/Rex Shutterstock</p></div>
<div type="text">
<p>Krigen om avokadoen - en frukt som vokser på trær, selv om den kan minne om en grønnsak - har pågått i årevis i Mexicos vestlige delstat Michoacán, som ifølge The Guardian står for åtti prosent av USAs avokadoimport.</p>
<p>Nå drar det seg til, med tyverier i et omfang som produsentene ikke lenger kan leve med.</p>
<p>- De stjeler mellom sju og ti lastebiler i uka, sa David Ruiz, talsmann for APEAM, den nasjonale bransjeforeningen for produsenter og eksportører av avokado, til Mexico by-baserte Excelsior i mars.</p>
<p>Nå melder The Guardian at tyveriene noen dager er oppe i så mye som fire lastebiler.</p></div>
<div type="title" level="3">Enorme tap</div>
<div type="text">
<p>«Å mislykkes i å stoppe tyveriene av disse lastebilene vil gjøre en uopprettelig skade på avokadoindustrien», heter det i en reklamekampanje som ifølge Guardian ble publisert i meksikanske aviser fredag.</p>
<p>Hver av lastebilene tar åtte tonn, en last som ifølge Excelsior er verdt drøyt 90.000 kroner (200.000 meksikanske pesos). Da blir tapene store, i et land med et mye lavere prisnivå enn Norge.</p>
<p>«Det er umulig å fortsette å ta disse tapene», står det i annonsen som ble publisert på fredag.</p>
<p>Der oppfordres det til en offensiv mot bandittene, som i stor grad antas å tilhøre organiserte, kriminelle bander. Ofte ligger de i innbyrdes strid.</p>
<p>Slik har det vært i mange år. Michoacán er kjent som delstaten hvor den tidligere presidenten Felipe Calderón i 2006 innledet sin krig mot narkotikakartellene.</p></div>
<div type="title" level="3">Slåss med GPS</div>
<div type="text">
<p>For å begrense tapene, har produsentene tatt i bruk avansert teknologi. Blant annet forteller David Ruiz at en stjålet lastebil nå kan fjern-stoppes ved hjelp av GPS-signaler.</p>
<p>Problemet er at bandittene svarer med samme mynt, for å unngå at stjålne lastebiler påføres motorstopp.</p>
<p>- Nå har de teknologi som hindrer at det skal skje. De forbedrer seg altså, for det er åpenbart at hvis de gjør det godt med denne tyveri-forretningen, investerer de også for å kunne stjele med mindre risiko, sier Ruíz til Excelsior.</p>
<p>Inntil videre tyder ingenting på at avokado-krigen vil ta slutt med det første. Den bølger fram og tilbake, med erobrede og gjenerobrede lastebiler.</p></div>
<div type="title" level="3">- Gir seg aldri</div>
<div type="text">
<p>For tre uker siden var politiet som trakk det lengste strået, etter et tips på nødtelefonen 911, da de beslagla en stjålet, rød lastebil med åtte tonn avokado på veien mellom byene Pátzcuaro og Morelia.</p>
<p>«SSP (politiet) vil aldri gi seg på å slåss mot hvilken som helst handling mot sikkerheten til innbyggerne i Michoacán», forsikres det i artikkelen på nettstedet Quadratín.</p></div></body></document>

=== malinhauglandh/exploring-norwegian-news-sources/data/fv-2019-nob/FV-20190618-det-murres-i-brann-t.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="FV-20190618-det-murres-i-brann-t.xml"/>
<attribute name="url" value="http://www.fvn.no/sport/i/opVRrj/Det-murres-i-Brann-troppen-Det-er-verken-overraskende-eller-farlig" frk="42 0 0 311 %%"/>
<attribute name="source" value="FV"/>
<attribute name="date" value="2019-06-18 11:59"/>
<attribute name="author" value=""/>
<attribute name="gender" value="U"/>
<attribute name="class1" value="sport"/>
<attribute name="class2" value="sport"/>
<attribute name="language" value="nob"/>
</header>
<body>
<div type="title" level="1">«Det murres i Brann-troppen. Det er verken overraskende eller farlig.»</div>
<div type="ingress">KOMMENTAR: Spørsmålet er hvordan murringen blir håndtert, skriver Anders Pamer.</div>
<div type="author"></div>
<div type="date"></div>
<div type="caption"><p>KRITISK: Gilbert Koomson uttalte seg kritisk om trener Lars Arne Nilsen etter kampen mot Haugesund. FOTO: MARIUS SIMENSEN / BILDBYRÅN NORWAY</p></div>
</body></document>

=== malinhauglandh/exploring-norwegian-news-sources/data/sa-2019-nob/SA-20190903-tog-med-sovekup-er-o.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="SA-20190903-tog-med-sovekup-er-o.xml"/>
<attribute name="url" value="http://www.aftenbladet.no/forbruker/i/70QrVW/Tog-med-sovekup-er-opptil-dobbelt-sa-dyrt-som-en-flytur--pa-samme-strekning" frk="51 0 0 303 %%"/>
<attribute name="source" value="SA"/>
<attribute name="date" value="2019-09-03 14:33"/>
<attribute name="author" value=""/>
<attribute name="gender" value="U"/>
<attribute name="class1" value="forbruker"/>
<attribute name="class2" value=""/>
<attribute name="language" value="nob"/>
</header>
<body>
<div type="title" level="1">Tog med sovekupé er opptil dobbelt så dyrt som en flytur – på samme strekning</div>
<div type="ingress">Vi har sammenlignet prisene mellom Norwegian, SAS og Vy. Tog er både billigst og dyrest.</div>
<div type="author"></div>
<div type="date"></div>
<div type="caption"><p>Å reise med sovekupé i Norge er dyrere enn å fly. Collage: Gorm Kallestad, Berit Roald, Ole Berg-Rusten/ NTB scanpix</p></div>
</body></document>

=== malinhauglandh/exploring-norwegian-news-sources/data/da-2019-nob/DA-20190312-tolldirektoratet-far.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="DA-20190312-tolldirektoratet-far.xml"/>
<attribute name="url" value="http://www.dagsavisen.no/innenriks/tolldirektoratet-far-900-000-kroner-i-gebyr-fra-datatilsynet-for-ulovlig-overvaking-av-biler-1.1292393" frk="242 15 26 1660"/>
<attribute name="source" value="DA"/>
<attribute name="date" value="2019-03-12 20:46"/>
<attribute name="author" value="NTB"/>
<attribute name="gender" value="U"/>
<attribute name="class1" value="innenriks"/>
<attribute name="class2" value=""/>
<attribute name="language" value="nob"/>
</header>
<body>
<div type="title" level="1">Tolldirektoratet får 900.000 kroner i gebyr fra Datatilsynet for ulovlig overvåking av biler</div>
<div type="ingress">Tolldirektoratet må betale 900.000 kroner i overtredelsesgebyr etter å ha drevet ulovlig overvåking av flere millioner biler, slår Datatilsynet fast.</div>
<div type="author"></div>
<div type="date"></div>
<div type="caption"><p>Bjørn Erik Thon er direktør i Datatilsynet.</p></div>
<div type="text">
<p>NRK kunne i midten av februar fortelle at 80 millioner bilpasseringer er blitt videoovervåket uten hjemmel i loven. Nå har Datatilsynet konkludert i saken, etter å ha gransket den i flere måneder. Overvåkingen var ulovlig, slår Datatilsynet fast.</p>
<p>– Dette er det største overtredelsesgebyret vi noensinne har varslet, sier direktør Bjørn Erik Thon til .</p>
<p>Gebyret er fastsatt etter den gamle personvernloven som nå har blitt erstattet.</p>
<p>– Hadde vi vurdert lovbruddene opp mot den nye loven, hadde gebyret trolig blitt langt høyere, sier Thon.</p>
<p>Følg Dagsavisen på Facebook og Twitter!</p>
<p>Datatilsynet advarte allerede i mars 2017 om at Tolldirektoratets overvåking var inngripende for personvernet, og manglet hjemmel. I begynnelsen av 2018 varslet også Tolldirektoratets egne jurister om at overvåkingen var ulovlig.</p>
<p>mener etaten har brutt personopplysningsloven gjennom innsamling og bruk av opplysninger fra kameraer uten lov.</p>
<p>Datatilsynet sier de har lagt vekt på at Tolldirektoratet har overvåket 80 millioner passeringer, hvor antall berørte personer anslås til 7 – 8 millioner.</p>
<p>Tolletaten skal drive overvåking av grensekryssende trafikk, men de har også registrert og lagret data fra kameraer som Statens vegvesen har utplassert mange steder i landet. Dette er kameraer som Tolldirektoratet ikke skal ha tilgang til opplysninger fra, ifølge Datatilsynet.</p></div></body></document>

=== malinhauglandh/exploring-norwegian-news-sources/data/sa-2019-nob/SA-20190624-venstre-stavanger-tr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="SA-20190624-venstre-stavanger-tr.xml"/>
<attribute name="url" value="https://www.aftenbladet.no/lokalt/i/kJdk39/Venstre---Stavanger-trenger-en-egen-byarkitekt" frk="73 0 0 471 %%"/>
<attribute name="source" value="SA"/>
<attribute name="date" value="2019-06-24 13:18"/>
<attribute name="author" value=""/>
<attribute name="gender" value="U"/>
<attribute name="class1" value="lokalt"/>
<attribute name="class2" value="henrik lundberg,christian wedler,jan erik søndeland,bystyret,arkitektur,byutvikling,bergen,alexandria algard"/>
<attribute name="language" value="nob"/>
</header>
<body>
<div type="title" level="1">Venstre: - Stavanger trenger en egen byarkitekt</div>
<div type="ingress">– Vi bør gjøre som i Bergen, og få på plass en egen byarkitekt. I dag er ansvaret for byens utseende for spredt og i for stor grad overlatt til tilfeldigheter, sier Jan Erik Søndeland (V).</div>
<div type="author"></div>
<div type="date"></div>
<div type="caption"><p>Jan Erik Søndeland, ordførerkandidat for Stavanger Venstre, vil opprette en egen byarkitektavdeling i Stavanger kommune. Bakgrunnen er blant annet den store utbyggingen i Paradis, som er i startgropa. Jarle Aasland</p></div>
</body></document>

=== malinhauglandh/exploring-norwegian-news-sources/data/db-2019-nob/DB-20191014-stjernetrio-sto-over.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="DB-20191014-stjernetrio-sto-over.xml"/>
<attribute name="url" value="http://www.dagbladet.no/sport/stjernetrio-sto-over-siste-trening/71706464" frk="149 39 39 985"/>
<attribute name="source" value="DB"/>
<attribute name="date" value="2019-10-14 11:04"/>
<attribute name="author" value="NTB I"/>
<attribute name="gender" value="U"/>
<attribute name="class1" value="sport"/>
<attribute name="class2" value=""/>
<attribute name="language" value="nob"/>
</header>
<body>
<div type="title" level="1">Stjernetrio sto over siste trening</div>
<div type="ingress">Joshua King, Omar Elabdellaoui og Haitam Aleesami var ikke å se da de norske fotballherrene trente i Bucuresti mandag ettermiddag.</div>
<div type="author">NTB I</div>
<div type="date">2019-10-14</div>
<div type="caption"><p>STÅR OVER: Joshua King, her fra flyplassen i Bucure&#537;ti før EM-kvalifiseringskampen mot Romania. Foto: Stian Lysberg Solum / NTB Scanpix</p></div>
<div type="text">
<p>De tre spillerne, som alle spilte 90 minutter i 1-1-kampen mot Spania lørdag, trente alternativt på spillerhotellet.</p>
<p>Det får NTB opplyst fra landslagets medieansvarlige, Svein Graff.</p>
<p>Norge spiller bortekamp mot Romania tirsdag kveld. Kun seier er godt nok om håpet om direkte EM-plass skal leve videre.</p>
<p>EM-KVALIFISERING</p>
<p>Resterende kamper i Norges gruppe:</p>
<p>Tirsdag:</p>
<p>Sverige – Spania, Romania – Norge, Færøyene – Malta.</p>
<p>15. november:</p>
<p>Norge – Færøyene, Spania – Malta, Romania – Sverige.</p>
<p>18. november:</p>
<p>Sverige – Færøyene, Spania – Romania, Malta – Norge</p>
<p>Tabell</p>
<p>Spania 19 (18-4)</p>
<p>Sverige 14 (17-8)</p>
<p>Romania 13 (16-7)</p>
<p>Norge 10 (12-9)</p>
<p>Malta 3 (2-17)</p>
<p>Færøyene 0 (3-23)</p></div></body></document>

=== malinhauglandh/exploring-norwegian-news-sources/data/vg-2019-nob/VG-20191004-vipers-med-sjokknyhe.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="VG-20191004-vipers-med-sjokknyhe.xml"/>
<attribute name="url" value="http://www.vg.no/sport/i/K3kMBe/vipers-med-sjokknyhet-loeke-aktuell-for-spill-til-helgen" frk="465 2 6 2862"/>
<attribute name="source" value="VG"/>
<attribute name="date" value="2019-10-04 16:17"/>
<attribute name="author" value=""/>
<attribute name="gender" value="U"/>
<attribute name="class1" value="sport"/>
<attribute name="class2" value=""/>
<attribute name="language" value="nob"/>
</header>
<body>
<div type="title" level="1">Vipers med sjokknyhet: Løke aktuell for spill til helgen</div>
<div type="ingress">Heidi Løke (36) skal likevel ikke ha pådratt seg en alvorlig kneskade, og kan være tilbake på banen for Vipers allerede til helgen.</div>
<div type="author"></div>
<div type="date">Oppdatert nå nettopp</div>
<div type="caption"><p>COMEBACK: Heidi Løke er tilbake fra skade etter bare en uke. Her fra håndball-EM i Frankrike desember 2018. Foto: Bjørn S. Delebekk, VG.</p></div>
<div type="text">
<p>Det melder Fædrelandsvennen.</p>
<p>Løke skadet kneet forrige fredag. Da ble det meldt at hun ikke kom til å rekke VM i Japan i desember. Fredag trente hun likevel for fullt med Vipers. Forrige sesongs seriemester spiller første kamp i Champions League lørdag.</p>
<p>– Det er fantastisk. Dette hadde jeg ikke trodd. Det kjennes bra, sier Løke til avisen.</p>
<p>– Fikk du feil diagnose?</p>
<p>– Jeg vet ikke. Du må snakke med noen som har greie på det medisinske. Men alle kliniske undersøkelser er bra. Jeg fikk en vridning, men jeg tror det bare var en vridning, svarer strekspilleren.</p>
<p>– Det er noen medisinske vurderinger som skal gjøres, men det ser veldig bra ut, sier Vipers-trener Ole Gustav Gjekstad til Fædrelandsvennen.</p>
<p>– Jeg kan ikke forklare det medisinsk, men det er ingen tvil om at pressemeldingen som ble sendt ut var litt forhastet. Og at ting nå er mye bedre enn fryktet. Hvis medisinmennene er enige, er det ikke sikkert hun er ute i seks måneder likevel, fortsetter han.</p>
<p>Sjekk dette lekre innspillet til Løke fra forrige mesterskap:</p>
<p>Dette sier medisinsk ansvarlig i Vipers, Erik Welhaven Løchen, om mulighetene for spill:</p>
<p>– Nå er det slik at vi har testet Løke gradvis mer fra tirsdag. Torsdag trente hun håndball uten kroppskontakt, og fredag trente hun håndball uten restriksjoner. Så langt ser det positivt ut. Hun har ikke rapportert noe ubehag etter trening. Men endelig avgjørelse tar vi på kampdag.</p>
<p>– I etterkant av skaden under Intersport Cup ble det tatt MR-bilder av Heidis kne. Da mente vi å se en skade av den typen som ble beskrevet i opprinnelig melding. Heidi ble derfor anbefalt å ta operasjon, og henvist videre til ortoped. I mellomtiden ble imidlertid kneet hennes mye bedre, og ortopeden mente det virket som det ikke var samsvar mellom våre MR-funn, og den skaden Heidi kjente under Intersport Cup, sier landslagslege for kvinnene Anne Froholdt i en pressemelding på håndballforbundets sider.</p>
<p>Froholdt mener utslaget på MR-undersøkelsene kan ha kommet av en gammel skade eller noe annet.</p>
<p>Vipers møter FTC-Rail Cargo Hungaria i Champions League-gruppespillet lørdag.</p>
<p>Skaden oppsto da Løke skulle snu seg og løpe i forsvar under landskampen mot Brasil forrige fredag.</p>
<p>Dette er en svært gledelig opptur for håndballandslaget som allerede er svært skadeplaget. Seks spillere rekker trolig ikke mesterskapet: Katrine Lunde, Kari Aalvik Grimsbø, Nora Mørk, Kjerstin Boge Solås, Veronica Kristiansen og Amanda Kurtovic.</p>
<p>Også stortalentet Henny Reistad er usikker.</p>
<p>Her blir Løke presentert som Vipers-spiller:</p></div></body></document>

=== malinhauglandh/exploring-norwegian-news-sources/data/bt-2019-nob/BT-20190613-svein-ludvigsen-innr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="BT-20190613-svein-ludvigsen-innr.xml"/>
<attribute name="url" value="https://www.bt.no/nyheter/innenriks/i/K3bopo/Svein-Ludvigsen-innrommer-a-ha-loyet-for-politiet-og-ha-hatt-sex-med-fornarmet-i-straffesaken" frk="742 3 15 4270" ab="Nei"/>
<attribute name="source" value="BT"/>
<attribute name="date" value="2019-06-13 11:08"/>

<attribute name="author" value="NTB"/>
<attribute name="gender" value="m"/>
<attribute name="class1" value="nyheter,innenriks"/>
<attribute name="class2" value="Etterforskning"/>
<attribute name="language" value="nbo"/>
</header>
<body>
<div type="title" level="1">Svein Ludvigsen innrømmer å ha hatt sex med fornærmet i straffesaken</div>
<div type="ingress">Tidligere fylkesmann Svein Ludvigsen vedgår å ha løyet til politiet og innrømmer at han har hatt sex med en av de fornærmede i straffesaken mot ham.</div>
<div type="author">NTB</div>
<div type="date">13. juni 2019 11:08</div>
<div type="caption"><p>Svein Ludvigsen løy til politiet da han ble konfrontert med anklagene mot seg, men hevder han snakker sant når han nå sier han kun hadde frivillig sex med én av de tre fornærmede, og kun tre ganger. Foto: Tegning av rettstegner Ane Hem / NTB scanpix</p></div>
<div type="text">
<p>– Fornærmede og jeg har hatt flere former for seksuell kontakt, tre ganger, i Oslo. Men bare i Oslo, og ikke i det omfang og på de måter som han beskriver. Alle tre gangene har vært frivillig, uten tvang eller trusler på noen som helst måte, og slik jeg oppfatter det, så ville vi det begge to, sa Svein Ludvigsen da han forklarte seg for retten torsdag formiddag.</p>
<p>Den tidligere høyt betrodde Høyre-politikeren, fylkesmannen og statsråden hadde forberedt sin frie forklaring grundig og hadde et slags manus foran seg da han i en times tid fikk snakke så å si uavbrutt. Det knyttet seg på forhånd sto spenning til hva Ludvigsen ville si når han først fikk sjansen. Han har ikke offentlig gitt noen kommentarer om straffesaken mot seg, annet enn å svare nei på dommerens spørsmål om han erkjenner skyld etter tiltalen.</p>
<p>Der står det beskrevet detaljert hvordan han gjennom en seksårsperiode gjentatte ganger skal ha hatt seksuell omgang med en nå 25 år gammel mann, samt hvordan han ved noen enkeltanledninger skal ha hatt det med ytterligere to fornærmede. Felles for de tre er at de kom til Norge som asylsøkere, og at de nå hevder Ludvigsen misbrukte stilling sin og den tillit de hadde til ham til å skaffe seg seksuell omgang.</p>
<p>– De lyver. Jeg vil ikke spekulere og synse om hvilke motiver de har, sa Ludvigsen om de to siste fornærmede, to menn på 26 og 34 år.</p></div>
<div type="title" level="3">Innrømmer løgn</div>
<div type="text">
<p>Han innledet forklaringen med å fortelle om sjokket han opplevde da han ble pågrepet for halvannet år siden og tatt med til politihuset i Tromsø for avhør. Det var den «tankemessige lammelsen», som han beskrev situasjonen han var i, som kan ha medvirket til at han i de videre avhørene fullstendig avviste å ha hatt noen som helst seksuell omgang med mannen som er omtalt i tiltalens hovedpunkter.</p>
<p>– Det er særdeles vanskelig å innrømme, men jeg innrømmer at enkelte ting jeg sa på politihuset, ikke er riktig.</p>
<p>– Det må ses i sammenheng med den sjokktilstanden jeg var i og den krisen jeg sto i under arrestasjonen, glattcelleoppholdet og senere varetektsfengslingen. Jeg viklet meg inn i påstander som gjorde at jeg hadde malt meg selv inn i et hjørne. Jeg hadde snakket usant og malt meg inn i et hjørne jeg ikke kom meg ut av. Jeg ble min egen verste fiende, sa Ludvigsen.</p>
<p>Han beskrev de tre episodene med seksuell omgang betydelig mer nedtonet enn det som framgikk av forklaringen til fornærmede og som står beskrevet i tiltalen. Alle tre gangene ble det utført seksuelle handlinger etter et gjensidig ønske og samtykke, framholdt han. Ikke på noe tidspunkt skal han ha lagt noe press på fornærmede, brukt vold eller kommet med trusler.</p></div>
<div type="title" level="3"> – Ville bare hjelpe</div>
<div type="text">
<p>Riktignok bekreftet Ludvigsen at han hadde hatt hyppig og relativt omfattende kontakt med den nå 25 år gamle mannen etter at han kom til Nord-Norge som asylsøker, slik fornærmede også har forklart, men kontakten hadde utelukkende gode hensikter, hevdet han. Den daværende fylkesmannen skal ha hjulpet med stort og smått, som mat, jobber og 10.000 kroner til kjøreopplæring.</p>
<p>De hadde sett hverandre nakne ved et tilfelle under dusjing i fylkeshuset i Tromsø etter trening, men det skjedde ikke noe seksuelt den gangen, ifølge forklaringen hans. Og han bekreftet at fornærmede var med på hytta ved Andsvatnet – både alene med Ludvigsen og sammen med resten av familien.</p>
<p>– Det foregikk ikke seksuelle handlinger på hytta, ikke hjemme hos meg heller, framholdt Ludvigsen.</p>
<p>– Jeg begriper ikke at han får seg til å beskylde meg for vold. Jeg beredte veien for ham til utdanning og det meste, og det er jeg faktisk glad og stolt over i dag. Jeg har alltid villet bidra til at folk blir sett og at de lykkes, sa han.</p>
<p>Retten tok lunsj klokka 12. Ludvigsen fortsetter sin forklaring når retten settes igjen. Da er det aktor som skal stille ham spørsmål.</p></div></body></document>
