=== malinhauglandh/exploring-norwegian-news-sources/data/da-2019-nob/avis2.dtd
<!ELEMENT document (#PCDATA | header | body)*>
<!ENTITY amp "&#38;">
<!ENTITY ndash "&#150;">
<!ENTITY lsaquo "&#8249;">
<!ENTITY rsaquo "&#8250;">
<!ENTITY ldquo "&#8220;">
<!ENTITY rdquo "&#8221;">
<!ENTITY Scaron "&#352;">
<!ENTITY scaron "&#352;">
<!ENTITY hellip "&#8230;">
<!ENTITY euro "&#8364;">
<!ENTITY permil "&#8240;">
<!ENTITY pi "&#960;">
<!ELEMENT header (#PCDATA | attribute)*>
<!ELEMENT attribute (#PCDATA)>
<!ATTLIST attribute name CDATA #IMPLIED>
<!ATTLIST attribute value CDATA #IMPLIED>
<!ATTLIST attribute frk CDATA #IMPLIED>
<!ATTLIST attribute ab CDATA #IMPLIED>
<!ELEMENT body (#PCDATA | div)*>
<!ELEMENT div (#PCDATA | p | P | mt)*>
<!ATTLIST div type CDATA #IMPLIED>
<!ATTLIST div level CDATA #IMPLIED>
<!ELEMENT p (#PCDATA | s | word | mt | b | B | i | I | em | strong | EM | STRONG | quote)*>
<!ATTLIST p id CDATA #IMPLIED>
<!ELEMENT P (#PCDATA | s | word | mt | b | B | i | I | em | strong | EM | STRONG | quote)*>
<!ATTLIST P id CDATA #IMPLIED>
<!ELEMENT b (#PCDATA | word)*>
<!ATTLIST b class CDATA #IMPLIED>
<!ELEMENT B (#PCDATA | word)*>
<!ELEMENT mt (#PCDATA | word)*>
<!ELEMENT i (#PCDATA | word)*>
<!ELEMENT I (#PCDATA | word)*>
<!ELEMENT em (#PCDATA | word)*>
<!ELEMENT EM (#PCDATA | word)*>
<!ELEMENT strong (#PCDATA | word)*>
<!ELEMENT STRONG (#PCDATA | word)*>
<!ELEMENT quote (#PCDATA | word)*>

<!-- Elements for grammatically tagged xml files -->
<!ATTLIST s admin CDATA #IMPLIED>
<!ELEMENT word (#PCDATA)>
<!ATTLIST word lemma CDATA #IMPLIED>
<!ATTLIST word features CDATA #IMPLIED>
<!ATTLIST word norm CDATA #IMPLIED>

=== malinhauglandh/exploring-norwegian-news-sources/data/aa-2019-nob/AA-20191030-kontroversiell-yogab.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="AA-20191030-kontroversiell-yogab.xml"/>
<attribute name="url" value="http://www.adressa.no/100Sport/sprek/Kontroversiell-yogabok-skapte-stor-oppmerksomhet-For-Gunhild-43-ble-yoga-vendepunktet-280822b.html" frk="88 3 2 581 %%"/>
<attribute name="source" value="AA"/>
<attribute name="date" value="2019-10-30 19:16"/>
<attribute name="author" value=""/>
<attribute name="gender" value="U"/>
<attribute name="class1" value="sport,sprek"/>
<attribute name="class2" value=""/>
<attribute name="language" value="nob"/>
</header>
<body>
<div type="title" level="1">Kontroversiell yogabok skapte stor oppmerksomhet. For Gunhild (43) ble yoga vendepunktet.</div>
<div type="ingress">– Yoga reddet livet mitt, forteller Gunhild Merete Giil Desilets.</div>
<div type="author"></div>
<div type="date">30.10.2019 19:16</div>
<div type="caption"><p>– Pust inn kjærlighet og pust ut kjærlighet. Pust inn kjærlighet til deg, og pust ut kjærlighet til andre og din omverden, er et av yogauttrykkene Gunhild bruker under timene sine. Foto: ODD MEHUS</p></div>
<div type="text">
<p>Gunhild Merete Giil Desilets ønsker de oppmøtte deltagerne velkommen til dagens yogatime. De står oppstilt på hver sin turkise yogamatte, klar for å ta imot instrukser om hvilke yoga-positurer de skal utføre.</p></div></body></document>

=== malinhauglandh/exploring-norwegian-news-sources/data/dn-2019-nob/DN-20190905-underleder-terningka.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="DN-20190905-underleder-terningka.xml"/>
<attribute name="url" value="http://www.dn.no/underleder/underleder-terningkast/2-1-666681" frk="25 5 1 181 %%"/>
<attribute name="source" value="DN"/>
<attribute name="date" value="2019-09-05 17:52"/>
<attribute name="author" value="Leder DN"/>
<attribute name="gender" value="U"/>
<attribute name="class1" value="underleder"/>
<attribute name="class2" value="Meninger,Underleder"/>
<attribute name="language" value="nob"/>
</header>
<body>
<div type="title" level="1">Underleder: Terningkast</div>
<div type="ingress">KrF-leder Kjell Ingolf Ropstad får terningkast én av Dagbladet og terningkast fire av VG for innsatsen i TV 2s partilederdebatt i Bergen.</div>
<div type="author">Leder DN</div>
<div type="date">2019-09-05 17:52</div>
<div type="caption"></div>
<div type="text">
</div></body></document>

=== malinhauglandh/exploring-norwegian-news-sources/data/nl-2019-nob/NL-20190722-bilhavari-pa-sandnes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="NL-20190722-bilhavari-pa-sandnes.xml"/>
<attribute name="url" value="http://www.nordlys.no/sandnessundbrua/tromso/trafikk/bilhavari-pa-sandnessundbrua/s/5-34-1166020" frk="86 7 4 557"/>
<attribute name="source" value="NL"/>
<attribute name="date" value="2019-07-22 15:58"/>
<attribute name="author" value="Magnus Aamo Holte"/>
<attribute name="gender" value="M"/>
<attribute name="class1" value=""/>
<attribute name="class2" value=""/>
<attribute name="language" value="nob"/>
</header>
<body>
<div type="title" level="1">Bilhavari på Sandnessundbrua</div>
<div type="ingress"></div>
<div type="author">Av Magnus Aamo Holte</div>
<div type="date">22. juli 2019, kl. 15:58</div>
<div type="caption"><p>DIRIGERER: Politiet rykket ut for å sørge for en smidig trafikkavvikling etter bilstansen på Sandnessundbrua rett før klokka 16 mandag. Foto: privat</p></div>
<div type="text">
<p>En bil har havarert på Sandnessundbrua rett før klokken 16 mandag ettermiddag.</p>
<p>- Bilen har kjørt i retning Tromsøya, og står på Kvaløyasiden. Vi rykker ut for å se til at trafikkavviklingen går så smidig som mulig i påvente av at bilen blir fjernet. Bilberger er på stedet, og trafikken bør snart gå som normalt i begge retninger, melder Troms politidistrikt.</p></div></body></document>

=== malinhauglandh/exploring-norwegian-news-sources/data/sa-2019-nob/SA-20190219-forsker---barn-ma-la.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="SA-20190219-forsker---barn-ma-la.xml"/>
<attribute name="url" value="http://www.aftenbladet.no/lokalt/i/bK0Va5/Forsker---Barn-ma-lare-seg-a-gjore-lekser-alene" frk="42 0 0 268 %%"/>
<attribute name="source" value="SA"/>
<attribute name="date" value="2019-02-19 14:48"/>
<attribute name="author" value=""/>
<attribute name="gender" value="U"/>
<attribute name="class1" value="lokalt"/>
<attribute name="class2" value="skole og utdanning,gjesdal kommune,skole"/>
<attribute name="language" value="nob"/>
</header>
<body>
<div type="title" level="1">Forsker: – Barn må lære seg å gjøre lekser alene</div>
<div type="ingress">Lekser gitt på riktig måte virker, mener forsker Thomas Nordahl.</div>
<div type="author"></div>
<div type="date"></div>
<div type="caption"><p>Leksene bør ikke være vanskeligere enn at eleven kan løse dem uten hjelp fra foreldrene, mener forsker Thomas Nordahl. Pål Christensen</p></div>
</body></document>

=== malinhauglandh/exploring-norwegian-news-sources/data/da-2019-nob/DA-20190221-city-snudde-til-seie.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="DA-20190221-city-snudde-til-seie.xml"/>
<attribute name="url" value="http://www.dagsavisen.no/sport/city-snudde-til-seier-med-ti-spillere-1.1281583" frk="55 17 6 351 %%"/>
<attribute name="source" value="DA"/>
<attribute name="date" value="2019-02-21 20:47"/>
<attribute name="author" value="NTB"/>
<attribute name="gender" value="U"/>
<attribute name="class1" value="sport"/>
<attribute name="class2" value=""/>
<attribute name="language" value="nob"/>
</header>
<body>
<div type="title" level="1">City snudde til seier med ti spillere</div>
<div type="ingress">FC Schalke - Manchester City 2-3). Manchester City ble redusert til ti mann på 1-2, men to sene scoringer fra Leroy Sané og Raheem Sterling ga de lyseblå 3-2 borte mot Schalke i mesterligaen.</div>
<div type="author"></div>
<div type="date"></div>
<div type="caption"><p>Manchester City tok med seg et godt utgangspunkt før returoppgjøret i åttedelsfinalen i mesterligaen.</p></div>
<div type="text">
</div></body></document>

=== malinhauglandh/exploring-norwegian-news-sources/data/da-2019-nob/DA-20190925-tidligere-danske-ban.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="DA-20190925-tidligere-danske-ban.xml"/>
<attribute name="url" value="http://www.dagsavisen.no/innenriks/tidligere-danske-bank-sjef-funnet-dod-i-estland-1.1590519" frk="114 27 20 735"/>
<attribute name="source" value="DA"/>
<attribute name="date" value="2019-09-25 20:46"/>
<attribute name="author" value="NTB"/>
<attribute name="gender" value="U"/>
<attribute name="class1" value="innenriks"/>
<attribute name="class2" value=""/>
<attribute name="language" value="nob"/>
</header>
<body>
<div type="title" level="1">Tidligere Danske Bank-sjef funnet død i Estland</div>
<div type="ingress">Den tidligere sjefen for Danske Banks avdeling i Estland, Aivar Rehe, er funnet død, opplyser estisk politi.</div>
<div type="author"></div>
<div type="date"></div>
<div type="caption"><p>Illustrasjonsfoto.</p></div>
<div type="text">
<p>56-åringen ble meldt savnet fra sitt hjem mandag og estisk politi har lett etter ham siden.</p>
<p>Aivar Rehe var sjef for Danske Banks estiske avdeling fra 2006 til 2015.</p>
<p>Den danske avisen Berlingske avslørte i 2017 at store beløp hadde passert gjennom den estiske banken uten at prosedyrer for å avsløre hvitvasking ble fulgt.</p>
<p>En intern gransking viste at det dreide seg om transaksjoner for nærmere 2.000 milliarder kroner, og en analyse utført av Jyske Bank konkluderte med at opptil 86 prosent av disse transaksjonene kunne være hvitvasking.</p></div></body></document>

=== malinhauglandh/exploring-norwegian-news-sources/data/vg-2019-nob/VG-20190918-mdg-far-bydelsmakt-i.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="VG-20190918-mdg-far-bydelsmakt-i.xml"/>
<attribute name="url" value="http://www.vg.no/nyheter/innenriks/i/lAX9pM/mdg-faar-bydelsmakt-i-oslo-og-ordfoereren-i-vardoe" frk="494 22 65 2868"/>
<attribute name="source" value="VG"/>
<attribute name="date" value="2019-09-18 19:07"/>
<attribute name="author" value=""/>
<attribute name="gender" value="U"/>
<attribute name="class1" value="nyheter,innenriks"/>
<attribute name="class2" value=""/>
<attribute name="language" value="nob"/>
</header>
<body>
<div type="title" level="1">MDG får bydelsmakt i Oslo og ordføreren i Vardø</div>
<div type="ingress">Miljøpartiet De Grønne er største parti i bydeler med tilsammen 200.000 innbyggere i Oslo. Det gir betydelig makt i bydelsutvalgene.</div>
<div type="author"></div>
<div type="date">Oppdatert nå nettopp</div>
<div type="caption"><p>JUBLER: MDGs frontfigur Lan Marie Nguyen Berg hadde grunn til å feire valgnatten. Onsdag ble det klart at miljøpartiet ble størst i fire bydelsutvalg i Oslo Foto: Annemor Larsen</p> <p>BLIR ORDFØRER: Ørjan Jensen blir ordfører i Vardø, som den første ordføreren fra MDG. Foto: MDG/Thomas Ekström</p></div>
<div type="text">
<p>I tillegg er miljøpartiet populært langt i nord, onsdag ble det nemlig kjent at de får sin aller første ordfører – i Vardø.</p>
<p>I Oslo er MDG størst i bydelsutvalgene Grünerløkka (26,4 prosent), St. Hanshaugen (26,2 prosent), Sagene (25,2 prosent og Gamle Oslo (22,3 prosent. Det viser ferske tall fra Oslo kommune. På St. Hanshaugen får partiet riktignok like mange representanter som Høyre, begge får fire.</p>
<p>les også</p></div>
<div type="title" level="3">Leder: Best uten Rødt</div>
<div type="title" level="3"> – Fantastisk motiverende</div>
<div type="text">
<p>I disse fire bydelene bor det rett under 200.000 mennesker eller nesten like mange som i Trondheim.</p>
<p>– Dette er fantastisk motiverende og veldig, veldig gøy at vi er det største partiet i fire bydelsutvalg, og da er det naturlig at vi får bydelslederen, sier Einar Wilhelmsen, leder av MDG i Oslo, til VG.</p>
<p>les også</p></div>
<div type="title" level="3">Valgforsker om bråket: En regjering i oppløsning</div>
<div type="text">
<p>Han forteller at de i år er representert i alle Oslos 15 bydelsutvalg, noe de ikke var for fire år siden. Bydelsutvalg er bydelens folkevalgte organ og består av 15 medlemmer med varamedlemmer. Bydelsutvalget har ansvar for desentraliserte kommunale oppgaver og fører tilsyn og kontroll med bydelsadministrasjonen.</p>
<p>Bydelsutvalget har blant annet ansvar for sykehjem, barnehager, barnevern og hjemmesykepleie.</p></div>
<div type="title" level="3">Forhandlinger</div>
<div type="text">
<p>– Mye av grunnen til at vi går så kraftig frem i bydelsvalget handler om at folk liker politikken vår og at de de vil ha mer, sier Wilhelmsen.</p>
<p>– Så hva skal dere gi dem?</p>
<p>– Nå skal vi jo gå inn og forhandle med Ap og SV, så det kan jeg ikke si så mye om annet enn at vi skal jobbe for å få realisert det vi har lovet, sier Wilhelmsen. Og legger til;</p>
<p>– Jeg tror mange har merket at med De Grønne har man fått renere luft og tryggere skoleveier og at vi gjør det mulig å sykle dit man vil om man er åtte eller 80 år.</p>
<p>MDG endte opp som Vardøs nest største parti. Partiet fikk 23,2 prosent av stemmene – en økning på hele 10,7 prosentpoeng fra forrige lokalvalg, skriver NRK.</p>
<p>Etter forhandlinger er Sp, Høyre, SV og MDG er enige om et samarbeid og ordførerkjedet går til MDG og Ørjan Jensen.</p>
<p>I Vardø gjorde også Senterpartiet et kjempevalg og endte opp med 20,6 prosent av stemmene, mens SV også styrket seg. I en koalisjon med Høyre danker de dermed ut Arbeiderpartiet, som gikk tilbake med 13,1 prosentpoeng til 40,5 prosent.</p>
<p>I bydel Gamle Oslo bor det 55 683 personer, på St Hanshaugen 38 400, på Grünerløkka 60 844 og Sagene 43 801.</p></div></body></document>

=== malinhauglandh/exploring-norwegian-news-sources/data/sa-2019-nob/SA-20190114-forst-pisser-vi-pa-d.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="SA-20190114-forst-pisser-vi-pa-d.xml"/>
<attribute name="url" value="https://www.aftenbladet.no/meninger/kommentar/i/7lkjvW/Forst-pisser-vi-pa-dem_-og-sa-klager-vi-pa-at-de-lukter-vondt-Slik-graver-elitene-sin-egen-grav" frk="95 9 6 631 %%"/>
<attribute name="source" value="SA"/>
<attribute name="date" value="2019-01-14 12:05"/>
<attribute name="author" value=""/>
<attribute name="gender" value="U"/>
<attribute name="class1" value="meninger,kommentar"/>
<attribute name="class2" value="populisme,konspirasjonsteorier,samfunnsdebatt,falske nyheter,kommentator harald birkevold"/>
<attribute name="language" value="nob"/>
</header>
<body>
<div type="title" level="1">Først pisser vi på dem, og så klager vi på at de lukter vondt. Slik graver elitene sin egen grav</div>
<div type="ingress">KOMMENTAR: I den nye informasjonsalderen er det umulig å undertrykke alternative fortellinger. De må i stedet møtes med dannelse. Elitene graver sin egen grav ved å idioterklære dem som trues mest av globalisering og markedsliberale reformer.</div>
<div type="author"></div>
<div type="date"></div>
<div type="caption"><p>En kvinne sprayes ned med tåregass under en demonstrasjon i Paris 8. desember. Opptøyene mot president Emmanuel Macrons politikk stammer ikke fra blindt raseri og pøbelaktighet, men fra maktesløshet, skriver Aftenbladets kommentator Harald Birkevold. Yves Herman / X00380</p></div>
</body></document>
