=== malinhauglandh/exploring-norwegian-news-sources/data/da-2019-nob/avis2.dtd
<!ELEMENT document (#PCDATA | header | body)*>
<!ENTITY amp "&#38;">
<!ENTITY ndash "&#150;">
<!ENTITY lsaquo "&#8249;">
<!ENTITY rsaquo "&#8250;">
<!ENTITY ldquo "&#8220;">
<!ENTITY rdquo "&#8221;">
<!ENTITY Scaron "&#352;">
<!ENTITY scaron "&#352;">
<!ENTITY hellip "&#8230;">
<!ENTITY euro "&#8364;">
<!ENTITY permil "&#8240;">
<!ENTITY pi "&#960;">
<!ELEMENT header (#PCDATA | attribute)*>
<!ELEMENT attribute (#PCDATA)>
<!ATTLIST attribute name CDATA #IMPLIED>
<!ATTLIST attribute value CDATA #IMPLIED>
<!ATTLIST attribute frk CDATA #IMPLIED>
<!ATTLIST attribute ab CDATA #IMPLIED>
<!ELEMENT body (#PCDATA | div)*>
<!ELEMENT div (#PCDATA | p | P | mt)*>
<!ATTLIST div type CDATA #IMPLIED>
<!ATTLIST div level CDATA #IMPLIED>
<!ELEMENT p (#PCDATA | s | word | mt | b | B | i | I | em | strong | EM | STRONG | quote)*>
<!ATTLIST p id CDATA #IMPLIED>
<!ELEMENT P (#PCDATA | s | word | mt | b | B | i | I | em | strong | EM | STRONG | quote)*>
<!ATTLIST P id CDATA #IMPLIED>
<!ELEMENT b (#PCDATA | word)*>
<!ATTLIST b class CDATA #IMPLIED>
<!ELEMENT B (#PCDATA | word)*>
<!ELEMENT mt (#PCDATA | word)*>
<!ELEMENT i (#PCDATA | word)*>
<!ELEMENT I (#PCDATA | word)*>
<!ELEMENT em (#PCDATA | word)*>
<!ELEMENT EM (#PCDATA | word)*>
<!ELEMENT strong (#PCDATA | word)*>
<!ELEMENT STRONG (#PCDATA | word)*>
<!ELEMENT quote (#PCDATA | word)*>

<!-- Elements for grammatically tagged xml files -->
<!ATTLIST s admin CDATA #IMPLIED>
<!ELEMENT word (#PCDATA)>
<!ATTLIST word lemma CDATA #IMPLIED>
<!ATTLIST word features CDATA #IMPLIED>
<!ATTLIST word norm CDATA #IMPLIED>

=== malinhauglandh/exploring-norwegian-news-sources/data/sa-2019-nob/SA-20190718-stortalent-17-fra-st.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="SA-20190718-stortalent-17-fra-st.xml"/>
<attribute name="url" value="http://www.aftenbladet.no/sport/i/naByzo/Stortalent-17-fra-Stavanger-rok-ut-av-EM-Om-to-uker-vil-hun-sla-tilbake" frk="81 41 18 439 %%"/>
<attribute name="source" value="SA"/>
<attribute name="date" value="2019-07-18 15:02"/>
<attribute name="author" value=""/>
<attribute name="gender" value="U"/>
<attribute name="class1" value="sport"/>
<attribute name="class2" value="stavanger,friidrett"/>
<attribute name="language" value="nob"/>
</header>
<body>
<div type="title" level="1">Stortalent (17) fra Stavanger røk ut av EM. Om to uker vil hun slå tilbake.</div>
<div type="ingress">Skjalgs Sara Busic (17) var litt skuffet over at hun ikke klarte å komme seg videre fra 800 meter under U20-EM i Boräs. Men hun var klar på å slå tilbake senere i sesongen.</div>
<div type="author"></div>
<div type="date"></div>
<div type="caption"><p>Sara Busic, til venstre, klarte ikke å ta seg videre fra forsøksheatet på 800 meter. Her sammen med Andrea Modin Engesæth, som skal løpe 1500 under EM U20 i Boräs. Privat</p></div>
</body></document>

=== malinhauglandh/exploring-norwegian-news-sources/data/ap-2019-nob/AP-20191017-bamba-utestengt-dage.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="AP-20191017-bamba-utestengt-dage.xml"/>
<attribute name="url" value="http://www.aftenposten.no/sport/fotball/i/4qGJPo/Bamba-utestengt-dager-etter-basketak-med-Berisha" frk="117 0 0 719"/>
<attribute name="source" value="AP"/>
<attribute name="date" value="2019-10-17 11:51"/>
<attribute name="author" value="Mads Bøyum"/>
<attribute name="gender" value="M"/>
<attribute name="class1" value="sport,fotball"/>
<attribute name="class2" value=""/>
<attribute name="language" value="nob"/>
</header>
<body>
<div type="title" level="1">Bamba utestengt dager etter basketak med Berisha</div>
<div type="ingress">Daouda Bamba får ikke være med Brann til kampen mot Sarpsborg søndag. Tidligere denne uken havnet han i krangel med spisskollega Veton Berisha.</div>
<div type="author">Mads Bøyum</div>
<div type="date">17.okt.2019 13:51</div>
<div type="caption"><p>FOTO: Jan Kåre Ness / NTB scanpix UTESTENGT: Daouda Bamba er utestengt fra Branns kamptropp mot Sarpsborg. Denne uken var han og Veton Berisha i konflikt på trening.</p></div>
<div type="text">
<p>Mandag oppsto det en konflikt på trening mellom Branns to stjerneangripere, Daouda Bamba og Veton Berisha.</p>
<p>Berisha skal ha snakket med Bamba om det som foregikk under forrige kamp mot Molde, da treneren vurderte Bamba som «ikke klar til å komme inn». Under treningen gikk Bamba så hardt til i en takling mot Berisha at det vakte reaksjoner.</p></div></body></document>

=== malinhauglandh/exploring-norwegian-news-sources/data/nl-2019-nob/NL-20190816-her-er-de-mest-lonns.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="NL-20190816-her-er-de-mest-lonns.xml"/>
<attribute name="url" value="http://www.nord24.no/tromso/troms/okonomi-og-naringsliv/her-er-de-mest-lonnsomme-spisestedene-i-hele-fylket-linn-a-29-tjener-mest-penger-av-alle-i-bransjen/s/5-32-126754" frk="52 14 5 339"/>
<attribute name="source" value="NL"/>
<attribute name="date" value="2019-08-16 19:02"/>
<attribute name="author" value="Rune Endresen"/>
<attribute name="gender" value="M"/>
<attribute name="class1" value=""/>
<attribute name="class2" value=""/>
<attribute name="language" value="nob"/>
</header>
<body>
<div type="title" level="1">Her er de mest lønnsomme spisestedene i hele fylket: Linnèa (29) tjener mest penger av alle i bransjen</div>
<div type="ingress">Stor oversikt over 145 spisesteder i Troms med rangering av lønnsomhet, inntekter og overskudd. Noen nykommere kan vise frem eventyrlige overskudd, mens andre og velkjente aktører sliter tungt - og må tåle svære tap.</div>
<div type="author">Av Rune Endresen</div>
<div type="date">16. august 2019, kl. 19:02</div>
<div type="caption"></div>
</body></document>

=== malinhauglandh/exploring-norwegian-news-sources/data/fv-2019-nob/FV-20190417-varsler-knallvar-pa-.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="FV-20190417-varsler-knallvar-pa-.xml"/>
<attribute name="url" value="http://www.fvn.no/nyheter/lokalt/i/zGl0r4/Meteorologene-om-Sorlandet-Sol_-bare-sol" frk="54 0 0 323 %%"/>
<attribute name="source" value="FV"/>
<attribute name="date" value="2019-04-17 18:46"/>
<attribute name="author" value=""/>
<attribute name="gender" value="U"/>
<attribute name="class1" value="nyheter,lokalt"/>
<attribute name="class2" value="nyheter,lokalt"/>
<attribute name="language" value="nob"/>
</header>
<body>
<div type="title" level="1">Varsler knallvær på Sørlandet ut påska</div>
<div type="ingress">Sola har for lengst meldt sin ankomst i Sør-Norge, og den har planer om å bli gjennom hele påska. Snart kommer også varmen, skal vi tro meteorologene.</div>
<div type="author"></div>
<div type="date"></div>
<div type="caption"><p>Sol så langt øyet kan se, på skitur på Hovden. Bildet er tatt ved en tidligere anledning. FOTO: Bjelland, Kjartan</p></div>
</body></document>

=== malinhauglandh/exploring-norwegian-news-sources/data/bt-2019-nob/BT-20190709-sandviken-kapteinen-.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="BT-20190709-sandviken-kapteinen-.xml"/>
<attribute name="url" value="https://www.bt.no/sport/i/JoL0Rb/Sandviken-kapteinen-enig-med-AC-Milan" frk="288 1 3 1704" ab="Nei"/>
<attribute name="source" value="BT"/>
<attribute name="date" value="2019-07-09 15:18"/>

<attribute name="author" value="NTB"/>
<attribute name="gender" value="m"/>
<attribute name="class1" value="sport"/>
<attribute name="class2" value="IL Sandviken,AC Milan"/>
<attribute name="language" value="nbo"/>
</header>
<body>
<div type="title" level="1">Sandviken-kapteinen enig med AC Milan</div>
<div type="ingress">Sandvikens kaptein Stine Hovland er enig med AC Milan om sine personlige betingelser for en overgang.</div>
<div type="author">NTB</div>
<div type="date">9. juli 2019 15:18</div>
<div type="caption"><p>TIL ITALIA: Sandviken-kaptein Stine Hovland var en del av den norske troppen i fotball-VM i Frankrike. FOTO: Bjørn Erik Larsen</p></div>
<div type="text">
<p>Dermed er det opp til klubbene å bli enige, skriver Bergensavisen.</p>
<p>Styreleder i Sandviken, Pål Hansen, sier derimot at Sandviken ikke har hørt noe fra den italienske storklubben.</p>
<p>– Vi ønsker gjerne å være åpen om ting som skjer i Sandviken, men akkurat her er det ingenting å melde. Vi har ikke mottatt bud fra dem eller noe andre klubber, sier Hansen til Bergens Tidende.</p>
<p>Milan gjorde nylig unna sin første sesong i den italienske toppdivisjonen. I likhet med flere storlag i Europa satser klubben også på damene.</p>
<p>28 år gamle Hovland har kontrakt med Sandviken ut året. Hun kan allerede nå signere for Milan fra 1. januar, uten at italienerne må betale overgangssum. AC Milans intensjon er at hun kan kjøpes fri allerede i sommer.</p>
<p>– Hun har vært en trofast spiller i seks år nå. Vi er alle innstilte på å gi Stine denne muligheten, men igjen, vi venter fortsatt på et bud fra AC Milan, sier Hansen.</p></div>
<div type="title" level="3"> – Agentstyrt</div>
<div type="text">
<p>Hansen sier at ingenting ligger i veien for at Hovland og AC Milan er enig om en personlig kontrakt.</p>
<p>– Det hele er agentstyrt. Det er en litt spesiell situasjon, for vi hørte om dette i påsken. Siden har vi ikke hørt noe. Vi må bare forholde oss til realiteten og den er at Stine Hovland er Sandviken-spiller, sier Hansen.</p>
<p>Styrelederen forventer at Sandviken vil være aktive på overgangsmarkedet i sommer.</p>
<p>Stine Hovland og agent Nils Christiansen har ikke besvart Bergens Tidendes gjentatte henvendelser.</p></div></body></document>

=== malinhauglandh/exploring-norwegian-news-sources/data/fv-2019-nob/FV-20190809-slar-tilbake-etter-t.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="FV-20190809-slar-tilbake-etter-t.xml"/>
<attribute name="url" value="http://www.fvn.no/sport/i/dOjXmO/Slar-tilbake-etter-trenerprofilenes-friskmelding-av-norsk-fotball--Litt-tidlig-a-sla-seg-pa-brystet" frk="83 3 2 542 %%"/>
<attribute name="source" value="FV"/>
<attribute name="date" value="2019-08-09 15:37"/>
<attribute name="author" value="Viljam Brodahl"/>
<attribute name="gender" value="M"/>
<attribute name="class1" value="sport"/>
<attribute name="class2" value="sport"/>
<attribute name="language" value="nob"/>
</header>
<body>
<div type="title" level="1">Slår tilbake etter trenerprofilenes «friskmelding» av norsk fotball: – Litt tidlig å slå seg på brystet</div>
<div type="ingress">Lars Bohinen, Erling Moe og Jostein Grindhaug er lei det negative fokuset. Ekspert mener det fortsatt er en «lang vei å gå» for norsk fotball.</div>
<div type="author">Viljam Brodahl</div>
<div type="date">09.aug.2019 15:37</div>
<div type="caption"><p>Aalesund-trener Lars Bohinen mener kritikken mot norsk fotball er uberettiget. FOTO: Faksimile / Svein Ove Ekornesvåg / NTB scanpix Leif Welhaven, kommentator i VG. Rosenborg slo Maribor overbevisende 3 – 1 på bortebane onsdag kveld. Carl-Erik Torp er fotballekspert for NRK.</p></div>
</body></document>

=== malinhauglandh/exploring-norwegian-news-sources/data/sa-2019-nob/SA-20191111-alle-har-noe-a-lare-.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="SA-20191111-alle-har-noe-a-lare-.xml"/>
<attribute name="url" value="http://www.aftenbladet.no/sport/i/JoXyMj/alle-har-noe-a-lre-av-molde-rosenborg-ogsa" frk="718 0 2 4220"/>
<attribute name="source" value="SA"/>
<attribute name="date" value="2019-11-11 10:44:46"/>
<attribute name="author" value="Ola Bernhus"/>
<attribute name="gender" value="M"/>
<attribute name="class1" value="sport"/>
<attribute name="class2" value=""/>
<attribute name="language" value="nob"/>
</header>
<body>
<div type="title" level="1">«Alle har noe å lære av Molde, Rosenborg også»</div>
<div type="ingress">KOMMENTAR: Moldes gull var ikke bare fortjent. MFK viser også vei ut fra det som ligner en sportslig krise i norske klubber.</div>
<div type="author">Ola Bernhus</div>
<div type="date">2019-11-11 10:44:46</div>
<div type="caption"><p>Molde sikret seriegullet på hjemmebane søndag. Svein Ove Ekornesvåg, NTB scanpix</p> <p>Moldes trener, Erling Moe, ser utover folkehavet i Molde under feiringen av seriegullet søndag. Assistenttrener Trond Strande til høyre.</p> <p>Det ble fest i Molde søndag kveld.</p> <p>Bodø/Glimt har tilført noe til norsk fotball i år, mener vår kommentator. Søndag møtte de Rosenborg.</p> <p>Brann har ikke overbevist denne sesongen, mener Ola Bernhus.</p></div>
<div type="text">
<p>Idrettslig var det bare to verdige gullkandidater i Eliteserien i år. Heldigvis vant en av dem.</p>
<p>Moldes seriemesterskap var ikke bare fortjent, de er også trøsten – kall det gjerne redningen – i en sesong der altfor mange lag ikke har bidratt til en sportslig utvikling. For manges vedkommende er det tvert imot.</p>
<p>Heldigvis har det i år vært få beskyldninger om at Molde bare er et kjøpelag. Riktig nok ville det vært vanskelig å oppnå en slik suksess (fire seriemesterskap de siste årene) uten pengene fra Røkke/Gjelsten, men det er noe annet som er viktig med Molde.</p>
<p>Svein Ove Ekornesvåg, NTB scanpix</p>
<p>Svein Ove Ekornesvåg, NTB scanpix</p>
<p>Holdningene, meningen med å spille fotball, viljen til å utvikle et angrepsspill som kan føre til noe større, forståelsen av at et fotballag må bygges med kløkt og tålmodighet, utført av spillere med talent, teknikk og forståelse.</p>
<p>Alle har noe å lære av Molde. Rosenborg også (midlertidig, bare vent til neste år).</p></div>
<div type="title" level="3">Og så Glimt da</div>
<div type="text">
<p>Bodø/Glimt er det andre laget som kunne ha fått et fortjent-stempel på gullmedaljer denne sesongen. I likhet med Molde er Glimt et lag som står for noe, som i gode kamper viser noe som kan bringe norsk klubbfotball fremover, som stiller med personligheter som gjør at vi kan glede oss til kampene deres.</p>
<p>SETT DENNE? RBK-helten tordnet på direktesendt TV: – Det er det verste som kan skje med en fotballklubb. Det er undergangen.</p>
<p>Ole Martin Wold, NTB scanpix</p>
<p>Også noen andre har levert en sesong det står respekt av, som Odd, Viking, Kristiansund, Haugesund, Stabæk og Tromsø. På hver sin måte har disse lagene utnyttet sine muligheter, spilt fotball som gir mening og vært konsistente sesongen igjennom.</p>
<p>Ja, Tromsø også, selv om de fortsatt er i faresonen. TIL er klubben som trassig har holdt fast på at fotballspillet er noe mer enn å vinne dueller og få ballen vekk. Selv for en klubb med spinklere forutsetninger må det være mulig å utvikle et spill som ligner på moderne idrett, mener de tydeligvis. Derfor er det viktig at TIL holder seg.</p></div>
<div type="title" level="3">De står på</div>
<div type="text">
<p>Så var det resten da. Om disse åtte lagene kan vi brutalt si – om vi ser dem hver for seg – at de ikke ville vært savnet. Bare som gruppe og kampmotstandere.</p>
<p>Rosenborg, Brann, Vålerenga og Strømsgodset ville blitt etterlyst i kraft av at de er storklubber fra storbyer og derfor skaffer oppmerksomhet, ikke minst når de svikter. Men ikke engang Rosenborg, fortsatt i medaljekampen, har i år tilført noe fotballmessig som er verdt å ta vare på.</p>
<p>Marit Hommedal, NTB scanpix</p>
<p>De tre andre nevnte har ikke engang vært spesielt interessante som skuffelser.</p>
<p>Klubber som Lillestrøm, Mjøndalen, Ranheim og Sarpsborg 08 har bare listet seg gjennom serien – ingen tilførsel av ekstra oppmerksomhet før de nå i sluttkampene kjemper for å unngå nedrykk, ingen spillemessige bidrag. Det er mulig å mene at Mjøndalen og Ranheim fortjener å overleve i Eliteserien fordi de trosser sin egen ressursmangel, men mest derfor.</p></div>
<div type="title" level="3">Ikke til å unngå</div>
<div type="text">
<p>Summert er det slik at halvparten av lagene ikke har gitt positive sportslige bidrag i årets serie. Det er ødeleggende for de andre også.</p>
<p>Men må det ikke alltid være slik? Vi kan vel ikke vente at alle skal gå sammen i en felles dugnad for å løfte det tekniske nivået i serien, utvikle et gjennomført pasningsspill, slippe frem unge spillere med nye holdninger. Nei, men flere kanskje.</p>
<p>Jevne og spennende kamper har vi, det skorter ikke der. Men den spenningen er like stor foran TV. Den som skal sitte på tribunen, ønsker noe mer.</p>
<p>Selv lag nede på tabellen bør føle en forpliktelse til å løfte sitt spill, av respekt for både egne tilhengere og den ligaen de deltar i.</p></div></body></document>

=== malinhauglandh/exploring-norwegian-news-sources/data/da-2019-nob/DA-20191009-ny-rapport-snus-unde.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "avis2.dtd" [<!ENTITY % HTMLsymbol SYSTEM "xhtml-symbol.ent"> %HTMLsymbol; ]>
<document>
<header>
<attribute name="file" value="DA-20191009-ny-rapport-snus-unde.xml"/>
<attribute name="url" value="http://www.dagsavisen.no/innenriks/ny-rapport-snus-under-svangerskapet-kan-pavirke-fosteret-negativt-1.1598359" frk="179 3 4 1210"/>
<attribute name="source" value="DA"/>
<attribute name="date" value="2019-10-09 20:46"/>
<attribute name="author" value="NTB"/>
<attribute name="gender" value="U"/>
<attribute name="class1" value="innenriks"/>
<attribute name="class2" value=""/>
<attribute name="language" value="nob"/>
</header>
<body>
<div type="title" level="1">Ny rapport: Snus under svangerskapet kan påvirke fosteret negativt</div>
<div type="ingress">Det er sannsynlig at risikoen for prematur fødsel øker dersom gravide bruker snus under svangerskapet, ifølge en ny rapport fra Folkehelseinstituttet.</div>
<div type="author"></div>
<div type="date"></div>
<div type="caption"></div>
<div type="text">
<p>Rapporten konkluderer med at det er mulig at gravide som snuser, øker risikoen for dødfødsel, keisersnitt, at den nyfødte har redusert kroppsvekst, får kortvarig pustestans, leppe- eller ganedefekter, og har økt mengde nedbrytningsprodukter av nikotin i urinen.</p>
<p>Knappe 20 prosent av norske menn og litt over 5 prosent av norske kvinner bruker snus daglig. Snusbruken i Norge har økt de siste tiårene, særlig blant unge voksne, og spesielt blant unge kvinner.</p></div>
<div type="title" level="3">Rapport</div>
<div type="text">
<p>Rapporten konkluderer også med at det er sannsynlig at snusbruk øker risikoen for kreft i spiserøret og bukspyttkjertelen, øker risikoen for diabetes type 2, og risikoen for å dø etter et hjerteinfarkt eller hjerneslag, samt høyner risikoen for metabolsk syndrom og høyt blodtrykk.</p>
<p>Snusrapporten er laget på oppdrag fra Helse- og omsorgsdepartementet. Den er basert gjennomgang av forskning på mennesker som bruker, snus sammenlignet med mennesker som ikke bruker snus, og flere andre typer studier. (NTB)</p></div></body></document>
